apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
spec:
  replicas: 1  # demo only; in prod I'd run HA with persistent storage
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.55.0
          ports:
            - containerPort: 9090
          args:
            - "--storage.tsdb.path=/prometheus"
          volumeMounts:
            - name: data
              mountPath: /prometheus
      volumes:
        - name: data
          emptyDir: {}  # quick lab storage; for prod use a PVC with retention
