---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy index page
  copy:
    dest: /var/www/html/index.html
    content: |
      <html><body><h1>Hello from Gabo's Ansible demo</h1></body></html>