name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ruff
        run: python -m pip install --upgrade pip && pip install ruff

      - name: Lint (ruff)
        run: ruff . || true
        # Using "|| true" so the workflow does not fail while the repo is still empty.
        # Later we can enforce strict linting rules and remove this.

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Validate (infra-as-code-aws) if folder exists
        if: ${{ hashFiles('infra-as-code-aws/**') != '' }}
        working-directory: infra-as-code-aws
        run: |
          terraform init -backend=false
          terraform validate
        # This step only runs if Terraform files exist inside "infra-as-code-aws".
        # "terraform init" uses "-backend=false" to avoid backend configuration during validation.
